README.md
changelog.md
mini-media-player.js
tracker.json

Fix mini-media-player.js?v=0.8.6:110:43 Uncaught SyntaxError: Missing } in template expression

Fix Missing } in template expression

---

package.json
rollup.config.js

Comments are already removed by rollup-plugin-terser

Remove rollup-plugin-cleanup

---

README.md

add linebreak to fix table in README

---

src/main.js

Fixes https://github.com/thomasloven/lovelace-popup-card/issues/17

Fix repeated popup-card issue

---

README.md
src/components/mediaControls.js
src/const.js
src/model.js

Following the discussion #167, the PR offer an option to display a stop button (hide by default).

feature: add option to hide/display a stop button

---

src/main.js
src/model.js

Remove usage of deprecated thumbnail api endpoint #244

---

src/model.js

Using `sync_volume` will now also sync mute.
Closes #262

Sync mute when sync_volume is enabled #262

---

src/components/tts.js

TTS input text color is hard to see when cover artwork is visible.
Closes #270

Fixed tts text color when artwork is present #270

---

src/components/dropdown.js
src/components/mediaControls.js
src/components/powerstrip.js
src/main.js
src/sharedStyle.js

Change icon button component for HA > 0.110.0 support.
resolves #297

:alien: Switch to ha-icon-button

---

src/style.js

Fix misaligned icons since HA 1.110.0
fixes #305

Fixes misaligned icons HA 1.110.0

---

src/model.js

Remove old bluesound service calls, in favor of the standardized ones.
Fixes #296

Fix broken Bluesound speaker management #296

---

src/components/shortcuts.js

Fix broken shortcut column height

---

README.md

Overwrite existing pymusiccast module to support speaker groups

Add yamaha musiccast support

---

src/style.js

Remove deprecated variable. 
This PR fixes #359.

Remove deprecated background values

---

src/components/groupList.js
src/components/powerstrip.js
src/components/tts.js
src/main.js
src/translations.js
src/utils/getLabel.js
src/utils/translation.js

Add support for card specific translations, feel free to submit translations for your language! 😄 
Closes #345

Add custom translation support

---

src/style.js

Fix webkit border radius issue #352

---

src/main.js

Fixed broken default artwork / icon

---

src/components/groupItem.js
src/translations.js

Added translation support for master string in speaker group management as requested in #377.

Add translation support for master string

---

src/style.js

Prevent jumping cover when transitioning artwork

---

README.md
src/components/mediaControls.js

Add support for slider volume steps #365

---

src/components/mediaControls.js
src/style.js

Do not override default slider container color

---

src/main.js

Fix artwork not clearing after playback

---

src/translations.js

After seeing how it looks in reality, some fixes are needed...

Hungarian fixes

---

src/translations.js

This PR adds Ukrainian translation.

Add Ukrainian translation

---

README.md
src/utils/handleClick.js

Option to open url in new tab #227

---

README.md
src/components/mediaControls.js
src/const.js

Add ability to display volume level #289

---

src/translations.js

Thanks for a really useful card! 
I am a Norwegian speaker and I have my hass in Norwegian. Therefore I proposed a Norwegian translation.
Best,
Kristoffer

Proposing a Norwegian translation

---

src/main.js

Fix scale option #415

---

README.md
src/components/powerstrip.js
src/const.js

Add `hide` option `state_label` for ability to hide state labels.
Fixes #316

Hide labels option #316

---

src/translations.js

Add CZ translation

---

.eslintrc.yml
src/main.js

I added the ability to select the card from the lovelace card picker (inspired by [this post](https://www.reddit.com/r/homeassistant/comments/jovt1l/usedevelop_custom_cards_your_card_could_be_in_the/))
I also had to add a line to eslintrc to allow the card to complie on my windows machine - not sure if this is needed, feel free to ignore if it's not

Added ability to select from lovelace card picker

---

src/editor.js
src/main.js
src/style.js
src/utils/config.js

Added support for visual editor. Some objects are not able to be edited in visual editor, there's a message at the bottom related to these.

Add visual editor support

---

src/components/checkbox.js

Reorder input and label elements

Fix checkbox label layout

---

src/components/checkbox.js
src/components/groupItem.js
src/components/groupList.js

* Self (current player) was not displayed in the list
* Checkboxes weren't properly checked on refresh
* Disabled element was not really disabled

Fix self not displaying and disabled items

---

src/utils/handleClick.js

Support for `fire-dom-event`

---

src/main.js

Fix missing player icon

---

src/translations.js

Russian translations.
Thanks EnQt.

Add russian translations

---

README.md

I was confused at first, and added this at the top-level, which didn't work obviously.
Maybe clarifying this in the documentation could help others with the initial configuration?

Clarify which section of configuration.yaml to edit

---

src/translations.js

Translation to Spanish
thanks @kalkih !

Translation to Spanish

---

README.md
src/components/mediaControls.js
src/const.js
src/model.js

Add support for repeat feature, will toggle between `off`, `all`, `one` repeat modes.
Fixes #431

Add repeat feature

---

README.md

Update simple install instructions

---

README.md
src/utils/handleClick.js

Adds haptics option for tap actions.
Should be supported in the HA IOS app.
Fixes #421

Add haptics support for tap_action

---

README.md
src/components/tts.js

Adds option for passing additional data / arguments to tts action.
Fixes #486

Add ability to pass additional data to tts action

---

src/sharedStyle.js

Hello! This simple PR will fix icons vertical-align after 2021.11.0 update. The previous version of the frontend will not be affected by this change.
#561

Fix icon valign

---

src/translations.js

https://github.com/kalkih/mini-media-player/blob/e29948cd25f1a6970e81cd821d3a9974e6000673/src/translations.js#L192-L210

Add chinese translations

---

README.md
src/components/tts.js

Speak message through any hass service.
```yaml
- type: custom:mini-media-player
entity: media_player.example
tts:
platform: service
data:
service: tts.edge_tts_say
service_data:
cache: true
- type: custom:mini-media-player
entity: media_player.xiaoai_speaker
tts:
platform: service
data:
service: xiaomi_miot.intelligent_speaker
service_data:
execute: true
silent: true
message_filed: text
```

Add tts platform: service

---

README.md
src/const.js
src/model.js

Add support for HEOS grouping after official HA integration added grouping support in v2021.12.

Add HEOS platform

---

src/components/dropdown.js

Fix dropdown not opening consistently

---

src/components/dropdown.js

Prevent dropdown from overflowing window

---

src/components/dropdown.js
src/editor.js
src/style.js

Fix broken selects in visual editor

---

src/model.ts

Ensure private attr is assigned prior to being accessed 
Fixes #658, #657

Fix attribute assignment

---

rollup.config.dev.js
rollup.config.js
src/utils/colorGenerator.js

Fix vibrant for rollup build

---

README.md

To reflect HA 2022.5.x and beyond.

Adjust path to resources config page

---

src/const.ts

Add `media_channel` in `MEDIA_INFO` to display channel name.

Add `media_channel` to `MEDIA_INFO`

---

src/translations.ts

Added Slovak translation

---

src/translations.ts

This adds the Hebrew translation.

Added Hebrew (he) translation

---

src/translations.ts

Added PT translation

---

src/style.ts

Details: https://github.com/kalkih/mini-media-player/pull/793#issuecomment-1841790400
Closes: #815

Fix border radius in full-cover mode

---

src/const.ts
src/main.ts

Use original entity icon by default

---

src/translations.ts

supplementing the Polish translation

Update PL translation

---

src/components/mediaControls.js
src/main.ts
src/style.ts

Fix volume slider on 2025.10

---

src/style.ts

Fix text overflow issue in media info on iOS
