kalkih/mini-media-player

README.md, mini-media-player.js
This enables to specify a TTS output entity and the output language.
See [TTS configuration](https://www.home-assistant.io/components/tts/#service-say)
=> Add extra configuration options TTS

README.md, src/main.js, src/model.js
Hi,
I love your mini-media-player card and its functionalities!
So much that I found it is now worth implementing the grouping of speakers for the yamaha_musiccast platform, now that we have a nice and intuitive interface.
As the speaker groups are currently only targetting sonos, could we have a more generic approach by specifying the platform?
I have developed the grouping services in the yamaha_musiccast exactly the same as the sonos join/unjoin services.
My implementation is here: [Update for yamaha_musiccast platform](https://github.com/hcoohb/home-assistant/tree/update-musiccast) 
I have not yet pushed it to hass as PR, as my PR on the pymusiccast module needs to happen first [here](https://github.com/jalmeroth/pymusiccast/pull/13)
I have tried to extend your work to have other …
=> Adding possibility to group speakers from different platform than sonos

README.md, changelog.md, package.json, src/style.js, tracker.json
`mmp-icon-color` was set to the same variable (`mini-media-player-base-color`) as `mmp-base-color` and `mmp-text-color` whereas not having the same fallback color (`paper-item-icon-color` vs. `primary-text-color` for both other).
this PR create a `mini-media-player-icon-color` that allows to consistently set an icon color different from those of base-color and text-color.
=> allow to set an icon color different than the text color

src/model.js
Hi!
With the snapcast component now handling multiroom, I realised that group handling wasn't supported by mini media player.
This changes aim to support snapcast mutiroom and future multiroom compatible components as they will have their own domain.
This is the first time I ever touch js so let me know if something is wrong!
Best regards
=> Updating group handling to support more platforms

README.md, src/style.js
Add an css variable in order to override the default stop color used by linear-gradient when artwork is defined to full-cover.
=> add style var to override linear color stop

README.md, src/components/shortcuts.js
I was missing the option to use a image on shortcut buttons. *(icons didn't cut it for me)*
=> adding image attribute for shortcuts

README.md, src/components/button.js, src/components/dropdown.js, src/components/mediaControls.js, src/components/powerstrip.js, src/components/shortcuts.js, src/components/soundMenu.js, src/components/sourceMenu.js, src/main.js, src/sharedStyle.js, src/style.js
Adds a new theme variable to adjust the scale of the card UI, this affects most of the cards elements and dimensions.
New theme variable is: `--mini-media-player-scale` and defaults to `40px`.
The value is basically the row height, each row of the card is allowed to take up this much height and the UI is scaled accordingly.
This variable can be set either in the user's theme which will apply it to all mmp cards or with card-mod in the `:host` selector to target individual cards.
```yaml
mini-media-player-scale: 50px
```
```yaml
...card config
style: |
:host {
--mini-media-player-scale: 50px;
}
```
Unsure if we should add this as a card option instead of as a theme variable, and if we should keep the value as pixels or change it to percentage, scale (e.g. 2, 2.5, 0.75) or any other unit, …
=> Scalable UI #156

README.md
I find it pretty difficult to spot the type:service option, and get it working with my Google Setup. I sadly wish to have Sonos around - however, with 6 Google devices, i'm not going to swap them, anytime soon.
So for everyon with Google, i guess this could be informative for other people, too.
Thanks for a great solution, btw :-) I guess you're taking my 1. place for the best custom module - that's for sure!
=> Added note about type:service + spotcast

src/model.js
Soundtouch multiroom requires some additional calls compared to most other platforms.
[DOCS](https://www.home-assistant.io/components/soundtouch/#service-soundtouch_add_zone_slave)
=> Support for Soundtouch multiroom

README.md, src/components/mediaControls.js, src/const.js
Adds `prev` & `next` hide options, to hide the previous and/or next playback button(s). 
Closes: #233
=> Options to hide previous and/or next playback controls #233

README.md, src/components/tts.js, src/main.js
Setting the tts `entity_id` to `group` will dynamically target the current speaker group for tts output.
```yaml
tts:
entity_id: group
...
```
Closes: #268
=> New tts entity_id parameter to target speaker group #268

src/components/progress.js
Progress tracking did not resume correctly after card was brought into view after being in the background.
Closes: #269
=> Resume progress tracking when re-connected #269

README.md
Since custom updater has been deprecated for a long while it should be dropped.
HACS is highlighted at the top so I don't think this should cause an issue.
=> Remove deprecated updating step

src/components/dropdown.js, src/components/shortcuts.js, src/main.js
Apparently the iron-icon element was also dropped in HA 1.110.0.
Switching to ha-icon instead.
Closes #302
=> Switch to new ha-icon element #302

README.md, package.json, src/components/shortcuts.js
Adds a cover option for shortcut items.
```yaml
shortcuts:
buttons:
- name: example
cover: /local/images/bg-example.jpg
...
```
closes #236
=> Shortcut cover image #236

.eslintrc.yml, README.md, src/main.js, src/model.js
Digged deeper into the HA core media player. As [volume_set service gets the volume_level float](https://github.com/home-assistant/core/blob/8cd905487e482e874a384c2e8a02070a53adfb95/homeassistant/components/media_player/__init__.py#L259) I assume it as the same behavior as the [check for mute support](https://github.com/kalkih/mini-media-player/blob/4925a6b7ccbb3da528f4d9fc870abf78e7b3834b/src/model.js#L185)
Then this should be the better version compared to #291
=> Add volume step control to volume buttons v2

README.md, src/const.js, src/model.js
Squeezebox doesn't have a slave/master setup like many other platforms so it requires some changes related to that functionality, now we set the card entity as the master, I'm not sure if this is the best solution.
Also, the service calls it uses are not the "standardized" ones, and there doesn't seem to be support for grouping multiple entities at once, at least not from looking at the documentation.
https://www.home-assistant.io/integrations/squeezebox/
Need to add documentation.
=> Squeezebox multiroom support

.eslintrc.yml, src/const.js, src/main.js, src/model.js, src/style.js, src/utils/misc.js
Fetch image artwork & save in Base64, use base64 image in rendering.
This prevents unwanted black / flickering / abrupt clearing artwork while it's loading.
Fixes #321
=> Fetch artwork & save in base64 before rendering it

README.md
Using [custom component](https://github.com/nagyrobi/home-assistant-custom-components-linkplay#multiroom) for sound devices based on Linkplay chipset. Moreover, the multiroom functionality was rewritten specifically to work with this lovelace card :-)
=> Add new platform to the supported speaker group tpyes

src/main.js
Add a fallback to the image url when failing fetching base64 image data
Resolves #385
=> Artowork relative url fallback

src/main.js
Update fallback logic to actually work.
`player.fetchArtwork` returns false instead of throwing error.
This happens to me when it's an external url which doesn't support CORS. I get a fetch error and then nothing happens.
It looks like the return value isn't used anymore so I removed that too.
=> Fix artwork fallback

README.md, src/const.js, src/main.js, src/model.js
I have a universal media_player which is setup with a sonos connect and external volume control (external amp).
In this case, it's not possible to benefit from the grouping feature offered by mmp. 
This PR introduces a new `real_player` parameter in the `speaker_group` object. If defined, it overrides the `entity` for everything related to group management.
This will work properly once #418 is fixed. (tested using the forked version on which I applied some fixes see https://github.com/mcguiresean/mini-media-player/pull/1)
Feedback appreciated :) (PR seems ugly though...)
=> Support for alternative current entity for groups

src/components/checkbox.js, src/components/groupItem.js, src/components/groupList.js, src/main.js
The checkbox element previously used is no longer imported by default in HA and depending on setup and usage might not always render in this card. We can therefore not rely on that element any more.
Fixes: #418
=> Switch to custom checkbox element

README.md
The custom integration that supports groups is called musiccast_yamaha. Changed the documentation to reflect that.
=> Changed yamaha_musiccast to musiccast_yamaha

src/editor.js
Remove `idle_view` option from card editor as it's miss configured and doesn't function properly.
Fixes: #468, #478
=> Remove idle_view from UI editor

src/model.js
Fixes #346 
I'm not sure why nobody made this fix before, maybe I'm missing something?
Tested with [yandex_station](https://github.com/AlexxIT/YandexStation) (custom component) and [cast](https://github.com/home-assistant/core/blob/dev/homeassistant/components/cast/media_player.py) (official from hass/core). Entities from these integrations have their `media_position_updated_at` attribute frozen after pausing, don't know about others. 
Freezing this attribute makes player position increase indefinitely. Checking if the player actually playing eliminates the problem.
=> Do not increment progress if player isn't playing

README.md, src/const.js, src/model.js, src/utils/config.js
HA has defined a new service schema for join and unjoin in the media_player component. Future (official) integrations will use these services instead of implementing join/unjoin in their domain.
To enable using these base services, the platform has to be set to media_player in the cards config, so that it offers full backward compatibility.
This was already requested in #519 and will also be needed in the future for other integrations (such as the rewritten official musiccast integration).
=> Added support for the new default grouping functionality

README.md, src/components/progress.js, src/const.js, src/main.js, src/utils/getProgress.js
Adds new display option `runtime_remaining`, to display remaining runtime of playing media.
Fixes #501
=> Add remaining runtime display option

README.md, src/components/mediaControls.js, src/const.js, src/model.js, src/utils/config.js
Added as an optional feature, disabled by default, see `jump` option in the `hide` option object.
Jump amount in seconds can be configured through the `jump_amount` feature, defaults to `10`.
Requires the entity to expose progress attributes, needed in order to calculate position to seek to.
This feature may be wonky on some media players depending on how well they update the progress, in particular in close conjunction with `media_seek` service calls.
Fixes #457
=> Jump feature

src/utils/config.js
The default value for jump_amount was set after destructuring yaml config, which caused it to override the configured value
=> (fix) Default jump_amount before destructure

src/components/mediaControls.js
Line 303 is preventing shuffle button icon from scaling with "scale" option.  Removing it allows resizing of shuffle button icon.
Testing was performed with the spotify integration enabled and the shuffle button shown.
=> Deleted Line 303

src/utils/translation.js
https://github.com/kalkih/mini-media-player/blob/e5ac7b5dcb2e713fab51128f962462af8cec04f6/src/translations.js#L1
But the language code returned by `hass.selectedLanguage || hass.language` with subtag in some regions, such as `zh-Hans` in China.
=> Fix translation for ISO 639-1

src/components/dropdown.js
For now migrating to mwc-menu.
In the future we should bundle the mwc elements with the card and not rely on HA defined elements in order to avoid breaking changes and compatibility issues.
=> Migrate to mwc-menu to support HA > 2022.3.X

src/sharedStyle.js
The move mwc-menu broke a CSS style.
=> fix: Vertical align on dropdown

src/components/dropdown.js
mwc-menu close event would bubble up in dom and potentially close higher up menus.
Closes #632
=> Fix dropdown closing other menus

README.md, src/config/types.ts, src/editor.js, src/main.ts
added image attribute to override icon with a URL.
=> Override icon with an image URL

src/model.ts
TS version against `dev` branch of https://github.com/kalkih/mini-media-player/pull/655
=> Adjust for breaking Sonos change in HA 2022.5 (TS version)

src/style.ts
Fixes #704. In Home Assistant version 2022.11, the material design language has shifted slightly and started utilizing an actual `border` css rule instead of the "border" intrinsically existing via the `box-shadow`. This fix just removes the `border` rule (leaving the existing `box-shadow` removal to be backwards-compatible with older HA versions).
=> Remove border set in HA 2022.11

src/style.ts
The default border-radius of `ha-card` is now 12px, which is causing the player contents to flow outside the card. Since the container needs `overflow: visible` to allow things like the source dropdown to expand beyond the player itself, it seems most appropriate to have the player contents respect the default. Perhaps this is a regression for older HA installs? Not sure what your stance is regarding maintaining backwards compatibility - worst case scenario I think is older installs could use the css variable `ha-card-border-radius` to override for their needs. However, I think going forward we should try to keep up-to-date with what the HA frontend is doing.
=> Update fallback border-radius to latest HA style

src/translations.ts
This PR aligns the translation of the `idle` state with the translation used in HA
=> Update PL translation

src/components/tts.js, src/style.ts
I decided to leave the standard HA style for the default state, with gray background.
Fixes #785
=> Fix TTS field after HA 2023.11.0 update

README.md, src/components/powerstrip.js, src/config/types.ts, src/const.ts
The new option allows to hide the group-button in the top right:
I can hide all the other elements in the topbar, but not the group button. Since I want to show the group all the time I don't need this button.
=> Add hide group-button option

src/editor.js
Should cover-fit in line 18 not be full-cover-fit? e.g., const OptionsArtwork = ['cover', 'full-cover', 'material', 'full-cover-fit', 'none'];
=> Fix `full-cover-fit` setting in the editor

src/const.ts, src/model.ts
**What**
Only show progress bar if media has a non-negative `media_duration` value
**Why**
Some media streams seem to report a negative `media_duration`, for example
http://lstn.lv/bbc.m3u8?station=bbc_6music&bitrate=320000 results in a `media_duration` of `-1`
Currently the progress bar displays for this stream, but if it gets tapped, an error is shown:
This change fixes that by hiding the progress bar if `media_duration` is below 0.
=> Only show progress if there is a non-negative `media_duration`
